# Generated by Django 5.2.8 on 2025-12-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='Роль',
            field=models.CharField(choices=[('designer', 'Дизайнер'), ('art_director', 'Арт Директор'), ('manager', 'Менеджер'), ('client', 'Клієнт')], default='client', max_length=20),
        ),
    ]
