# Generated by Django 5.2.8 on 2025-12-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_role_user_роль'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Роль',
            new_name='role',
        ),
    ]
