# Generated by Django 5.2.8 on 2025-12-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea_type',
            field=models.CharField(choices=[('pet-project', 'Pet-project'), ('header', 'Header design'), ('footer', 'Footer design'), ('landing', 'Landing page'), ('portfolio', 'Portfolio element')], default='pet-project', max_length=50),
        ),
    ]
