# Generated by Django 5.2.8 on 2025-12-09 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='Посилання на зображення')),
                ('thumbnail_url', models.URLField(max_length=500, verbose_name='Мініатюра')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опис/Alt')),
                ('source_id', models.CharField(max_length=100, verbose_name='ID на Unsplash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
